In [1]:
from numpy import *
a=array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [2]:
a.dtype

dtype('int32')

In [3]:
a.shape

(2, 4)

In [4]:
a.size

8

In [5]:
a.itemsize

4

In [6]:
a.nbytes

32

In [7]:
a.ndim

2

In [10]:
for row in a:
        print(row)

[0 1 2 3]
[4 5 6 7]


In [11]:
for elt in a.flat:
    print(elt)

0
1
2
3
4
5
6
7


In [12]:
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [13]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
a.resize((4,2))
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [15]:
a.swapaxes(1,2)
a

ValueError: bad axis2 argument to swapaxes

In [16]:
a.swapaxes(0,1)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [17]:
a.swapaxes(0,1)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [18]:
a.transpose()

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [19]:
a.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [20]:
b=array([1,2,3])
b.shape

(3,)

In [21]:
b.resize((1,3,1))
b

array([[[1],
        [2],
        [3]]])

In [22]:
b.shape

(1, 3, 1)

In [23]:
c=a.copy()
c

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [24]:
c[0][0]=-1
c

array([[-1,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7]])

In [25]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [26]:
c.fill(100)
c

array([[100, 100],
       [100, 100],
       [100, 100],
       [100, 100]])

In [27]:
a.tolist()

[[0, 1], [2, 3], [4, 5], [6, 7]]

In [28]:
a.tostring()

b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00'

In [29]:
a.astype(float)

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.]])

In [30]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [31]:
b=a.copy()

In [32]:
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [33]:
b.byteswap(False)

array([[        0,  16777216],
       [ 33554432,  50331648],
       [ 67108864,  83886080],
       [100663296, 117440512]])

In [34]:
a.view(dtype=int16)

array([[0, 0, 1, 0],
       [2, 0, 3, 0],
       [4, 0, 5, 0],
       [6, 0, 7, 0]], dtype=int16)

In [35]:
i=array([1+2j,3+4j,5+6j])
i.real

array([1., 3., 5.])

In [36]:
i.imag

array([2., 4., 6.])

In [37]:
i.conj()

array([1.-2.j, 3.-4.j, 5.-6.j])

In [38]:
i.conjugate()

array([1.-2.j, 3.-4.j, 5.-6.j])

In [40]:
a.dump("file.txt")

In [41]:
a.dumps()

b'\x80\x02cnumpy.core.multiarray\n_reconstruct\nq\x00cnumpy\nndarray\nq\x01K\x00\x85q\x02c_codecs\nencode\nq\x03X\x01\x00\x00\x00bq\x04X\x06\x00\x00\x00latin1q\x05\x86q\x06Rq\x07\x87q\x08Rq\t(K\x01K\x04K\x02\x86q\ncnumpy\ndtype\nq\x0bX\x02\x00\x00\x00i4q\x0cK\x00K\x01\x87q\rRq\x0e(K\x03X\x01\x00\x00\x00<q\x0fNNNJ\xff\xff\xff\xffJ\xff\xff\xff\xffK\x00tq\x10b\x89h\x03X \x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00q\x11h\x05\x86q\x12Rq\x13tq\x14b.'

In [42]:
a.tofile('foo.csv',sep=',',format="%s")

In [43]:
a.nonzero()

(array([0, 1, 1, 2, 2, 3, 3], dtype=int64),
 array([1, 0, 1, 0, 1, 0, 1], dtype=int64))

In [44]:
b=array([1, -5, 0, 20, 5, 11])
b.sort()
b

array([-5,  0,  1,  5, 11, 20])

In [45]:
b=array([4,9,10])
b.argsort(axis=-1)

array([0, 1, 2], dtype=int64)

In [46]:
a = array([1,3,4,6])
b = array([0,2,5])
a.searchsorted(b)

array([0, 1, 3], dtype=int64)

In [47]:
a = array([[4,1,3],[2,1,5]])
a.clip(0,2)

array([[2, 1, 2],
       [2, 1, 2]])

In [48]:
a = array([1.344, 2.449, 2.558])
a.round(decimals=2)

array([1.34, 2.45, 2.56])

In [49]:
a = array([[4,1,3],[2,1,5]])
a.cumsum(axis=None)

array([ 4,  5,  8, 10, 11, 16], dtype=int32)

In [50]:
a.cumprod(axis=None)

array([  4,   4,  12,  24,  24, 120], dtype=int32)

In [51]:
a = array([[4,1,3],[2,1,5]])
a.sum(axis=None)

16

In [52]:
a.prod(axis=None)

120

In [53]:
a.min(axis=None)

1

In [54]:
a.argmin(axis=None)

1

In [55]:
a.max(axis=None)

5

In [56]:
a.argmax(axis=None)

5

In [57]:
a.ptp(axis=None)

4

In [58]:
a.mean(axis=None)

2.6666666666666665

In [59]:
a.std(axis=None)

1.49071198499986

In [60]:
import os
os.remove('foo.csv')
os.remove('file.txt')