In [1]:
import numpy as np
a = np.array([[1,2,4],
              [2,5,3], 
              [7,8,9]])
A = np.mat(a)
A

matrix([[1, 2, 4],
        [2, 5, 3],
        [7, 8, 9]])

In [2]:
A=np.mat('1,2,3;4,5,6;7,8,9')
A

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
a = np.array([[ 1, 2],
              [ 3, 4]])
b = np.array([[10,20], 
              [30,40]])

np.bmat('a,b;b,a')

matrix([[ 1,  2, 10, 20],
        [ 3,  4, 30, 40],
        [10, 20,  1,  2],
        [30, 40,  3,  4]])

In [4]:
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [5]:
A * x

matrix([[14],
        [32],
        [50]])

In [7]:
print( A * A.I)

[[ 0.   1.  -0.5]
 [ 0.   2.  -1. ]
 [ 0.   3.   2.5]]


In [8]:
print( A ** 4)

[[ 7560  9288 11016]
 [17118 21033 24948]
 [26676 32778 38880]]
