In [2]:
import numpy as np
x=np.array([1,2,3])
y=np.array([4,5,6])
np.hypot(x,y)

array([4.12310563, 5.38516481, 6.70820393])

In [3]:
np.inf

inf

In [4]:
-np.inf

-inf

In [5]:
np.nan

nan

In [6]:
np.isinf(1.0)

False

In [7]:
np.array([0]) / 0.0

F:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan])

In [8]:
a = np.arange(5.0)
b = a / 0.0
b

F:\anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
F:\anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan, inf, inf, inf, inf])

In [10]:
b==np.nan

False

In [11]:
np.isnan(b)

True