In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
a=arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a.shape=2,5

In [4]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
a.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [6]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
shape(a)

(2, 5)

In [8]:
y = a[newaxis, :]
shape(y)

(1, 2, 5)

In [9]:
y = a[newaxis, newaxis, :]
shape(y)

(1, 1, 2, 5)

In [10]:
a = arange(6)
a.shape = (2,1,3)
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [11]:
b=a.squeeze()
b.shape

(2, 3)

In [12]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [13]:
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [14]:
a.T

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [15]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [16]:
a=arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [17]:
a.shape=3,4,5
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [18]:
b=a.T
print(b)
print(b.shape)

[[[ 0 20 40]
  [ 5 25 45]
  [10 30 50]
  [15 35 55]]

 [[ 1 21 41]
  [ 6 26 46]
  [11 31 51]
  [16 36 56]]

 [[ 2 22 42]
  [ 7 27 47]
  [12 32 52]
  [17 37 57]]

 [[ 3 23 43]
  [ 8 28 48]
  [13 33 53]
  [18 38 58]]

 [[ 4 24 44]
  [ 9 29 49]
  [14 34 54]
  [19 39 59]]]
(5, 4, 3)


In [19]:
a=arange(6)
a.shape=(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
b=a.T
b[0,1]=10
print(a)
print(b)

[[ 0  1  2]
 [10  4  5]]
[[ 0 10]
 [ 1  4]
 [ 2  5]]


In [21]:
x = array([
        [0,1,2],
        [10,11,12]
    ])
y = array([
        [50,51,52],
        [60,61,62]
    ])
print (x.shape)
print (y.shape)

(2, 3)
(2, 3)


In [22]:
z=concatenate((x,y))
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [23]:
z = concatenate((x,y), axis=1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [26]:
z = concatenate((x,y), axis=-1)
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [27]:
vstack((x, y)).shape

(4, 3)

In [28]:
hstack((x, y)).shape

(2, 6)

In [29]:
dstack((x, y)).shape

(2, 3, 2)

In [30]:
a = array([[0,1],
           [2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

In [31]:
b[0] = 88
print (b)
print (a)

[88  1  2  3]
[[0 1]
 [2 3]]


In [32]:
a.flat

In [33]:
b=a.flat
b[0]

0

In [34]:
b

In [35]:
b[0]=88
a

array([[88,  1],
       [ 2,  3]])

In [36]:
a.flat[:]

array([88,  1,  2,  3])

In [37]:
a = array([[0,1],
           [2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

In [38]:
b[0] = 10
a

array([[10,  1],
       [ 2,  3]])

In [39]:
a = array([[0,1],
           [2,3]])
aa = a.transpose()
b = aa.ravel()
b

array([0, 2, 1, 3])

In [41]:
b[0] = 10
aa

array([[0, 2],
       [1, 3]])

In [42]:
a

array([[0, 1],
       [2, 3]])

In [43]:
x = 1
atleast_1d(x)

array([1])

In [44]:
a = array([1,2,3])
b = atleast_2d(a)
b.shape

(1, 3)

In [46]:
c = atleast_3d(b)
c

array([[[1],
        [2],
        [3]]])