In [3]:
from numpy import *
a=array([1+1j,2+5.6j,3+4j,4])
a.dtype

dtype('complex128')

In [4]:
a.real

array([1., 2., 3., 4.])

In [5]:
a.imag

array([1. , 5.6, 4. , 0. ])

In [7]:
a.imag=[0,1,2,3]
a

array([1.+0.j, 2.+1.j, 3.+2.j, 4.+3.j])

In [8]:
a.conj()

array([1.-0.j, 2.-1.j, 3.-2.j, 4.-3.j])

In [9]:
a=array([0.,1,2,3])
a.dtype

dtype('float64')

In [10]:
a.real

array([0., 1., 2., 3.])

In [11]:
a.imag

array([0., 0., 0., 0.])

In [13]:
a.conj()

array([0., 1., 2., 3.])

In [14]:
a=array([0,3.4,5,6])
a.dtype

dtype('float64')

In [15]:
a.nbytes

32

In [17]:
a=array([0,3.5,6,7],dtype=float32)
a.dtype

dtype('float32')

In [18]:
a.nbytes

16

In [23]:
a = array([1,1.2,'hello', [10,20,30]], 
          dtype=object)
a*3

array([3, 3.5999999999999996, 'hellohellohello',
       list([10, 20, 30, 10, 20, 30, 10, 20, 30])], dtype=object)

In [24]:
a = array([1.5, -3], 
         dtype=float32)
a

array([ 1.5, -3. ], dtype=float32)

In [25]:
asarray(a, dtype=float64)

array([ 1.5, -3. ])

In [26]:
asarray(a, dtype=uint8)

array([  1, 253], dtype=uint8)

In [27]:
a

array([ 1.5, -3. ], dtype=float32)

In [28]:
b = asarray(a, dtype=float32)
b is a

True

In [29]:
a.astype(float64)

array([ 1.5, -3. ])

In [31]:
a.astype(uint8)

array([  1, 253], dtype=uint8)

In [32]:
b=a.astype(float32)
print(a)
print(b)

[ 1.5 -3. ]
[ 1.5 -3. ]


In [33]:
a is b

False

In [36]:
a=array((2,4,6,8),dtype=int32)
a

array([2, 4, 6, 8])

In [37]:
b=a.view(uint8)
b

array([2, 0, 0, 0, 4, 0, 0, 0, 6, 0, 0, 0, 8, 0, 0, 0], dtype=uint8)

In [39]:
a[0]=2**6
a

array([64,  4,  6,  8])

In [40]:
b

array([64,  0,  0,  0,  4,  0,  0,  0,  6,  0,  0,  0,  8,  0,  0,  0],
      dtype=uint8)