In [1]:
from numpy import *
lst=[0,1,2,3]
a=array(lst)
a

array([0, 1, 2, 3])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.dtype

dtype('int32')

In [4]:
a.itemsize

4

In [5]:
a.shape

(4,)

In [6]:
a.size

4

In [7]:
a.nbytes

16

In [8]:
a.ndim

1

In [19]:
a.fill(10.233)
a

array([10, 10, 10, 10])

In [20]:
a=array([2,4,6,8])
a[0]

2

In [22]:
a[0]=1
a

array([1, 4, 6, 8])

In [23]:
a[1:3]

array([4, 6])

In [24]:
a[::2]

array([1, 6])

In [25]:
od = array([21000, 21180, 21240, 22100, 22400])
dist = od[1:] - od[:-1]
dist

array([180,  60, 860, 300])

In [26]:
a = array([[ 0, 1, 2, 3],
           [10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [27]:
a.shape

(2, 4)

In [28]:
a.size

8

In [29]:
a.ndim

2

In [31]:
a[1,3]

13

In [32]:
a[1,3]=0
a

array([[ 0,  1,  2,  3],
       [10, 11, 12,  0]])

In [33]:
a[0]

array([0, 1, 2, 3])

In [34]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [35]:
a[1,3:6]

array([13, 14, 15])

In [36]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [37]:
a[:-1,2]

array([ 2, 12, 22, 32, 42])

In [39]:
a[2:3,1:4]

array([[21, 22, 23]])

In [40]:
a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [42]:
a = array([0,1,2,3,4])
b = a[2:4]
print(b)

[2 3]


In [44]:
b[0]=0
print(a)
print(b)

[0 1 0 3 4]
[0 3]


In [46]:
a = array([0,1,2,3,4])
b = a[2:4].copy()
b[0] = 10
print(a)
print(b)

[0 1 2 3 4]
[10  3]


In [48]:
a = arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [50]:
indices = [1, 2, -3]
y = a[indices]
print(y)

[10 20 70]


In [52]:
from numpy.random import rand
a = rand(10)
a

array([0.66637435, 0.84392779, 0.66232844, 0.31964201, 0.01486184,
       0.12893728, 0.0467797 , 0.51691366, 0.7037891 , 0.49286786])

In [53]:
mask=a>0.5
a[mask]

array([0.66637435, 0.84392779, 0.66232844, 0.51691366, 0.7037891 ])

In [54]:
a = array([[ 0, 1, 2, 3, 4, 5],
           [10,11,12,13,14,15],
           [20,21,22,23,24,25],
           [30,31,32,33,34,35],
           [40,41,42,43,44,45],
           [50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [55]:
a[(0,1,2,3,4), (1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

In [56]:
a[(0,1,2,3,4), (1,1,2,2,3)]

array([ 1, 11, 22, 32, 43])

In [57]:
a[3:, [0,2,5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [58]:
mask = array([1,0,1,0,0,1],
            dtype=bool)
a[mask, 2]

array([ 2, 22, 52])

In [60]:
a = arange(64)
a.shape = 4,4,4
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [61]:
y = a[:,:,[2, -1]]
y

array([[[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]],

       [[18, 19],
        [22, 23],
        [26, 27],
        [30, 31]],

       [[34, 35],
        [38, 39],
        [42, 43],
        [46, 47]],

       [[50, 51],
        [54, 55],
        [58, 59],
        [62, 63]]])

In [63]:
a = array([0, 12, 5, 20])
a>10

array([False,  True, False,  True])

In [64]:
where(a>10)

(array([1, 3], dtype=int64),)

In [65]:
indices = where(a > 10)
indices = indices[0]
indices

array([1, 3], dtype=int64)

In [67]:
a = array([[0, 12, 5, 20],
           [1, 2, 11, 15]])
loc = where(a > 10)
loc

(array([0, 0, 1, 1], dtype=int64), array([1, 3, 2, 3], dtype=int64))

In [68]:
a[loc]

array([12, 20, 11, 15])

In [69]:
a = arange(25)
a.shape = 5,5
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
where(a > 12)

(array([2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64),
 array([3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4], dtype=int64))