In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
names=array(['Tom','Jerry','Tony','Susan'])
weights=array([50,68,75,45])
sort(weights)

array([45, 50, 68, 75])

In [3]:
ordered_indices = argsort(weights)
ordered_indices

array([3, 0, 1, 2], dtype=int64)

In [4]:
weights[ordered_indices]

array([45, 50, 68, 75])

In [5]:
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[0.2, 0.1, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.6, 0.7]])

In [6]:
sort(a)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

In [8]:
a = array([
        [.2, .1, .5], 
        [.4, .8, .3],
        [.9, .6, .7]
    ])
a

array([[0.2, 0.1, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.6, 0.7]])

In [9]:
sort(a, axis = 0)

array([[0.2, 0.1, 0.3],
       [0.4, 0.6, 0.5],
       [0.9, 0.8, 0.7]])

In [10]:
sort(a, axis = 1)

array([[0.1, 0.2, 0.5],
       [0.3, 0.4, 0.8],
       [0.6, 0.7, 0.9]])

In [11]:
sorted_array = linspace(0,1,5)
values = array([.1,.8,.3,.12,.5,.25])

In [12]:
searchsorted(sorted_array, values)

array([1, 4, 2, 1, 2, 1], dtype=int64)

In [13]:
from numpy.random import rand
data = rand(100)
data.sort()

In [14]:
bounds = .4, .6
bounds

(0.4, 0.6)

In [16]:
low_idx, high_idx = searchsorted(data, bounds)
data[low_idx:high_idx]

array([0.4009665 , 0.41915892, 0.41938589, 0.42527783, 0.43134875,
       0.43276313, 0.45692281, 0.46237921, 0.46938938, 0.47152783,
       0.49642666, 0.50380343, 0.50718839, 0.53317708, 0.57655804,
       0.58457258, 0.59295357])