In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
a.shape=3,3
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [2]:
a.diagonal()

array([1, 5, 9])

In [3]:
a.diagonal(offset=1)

array([2, 6])

In [4]:
a.diagonal(offset=-1)

array([4, 8])

In [5]:
a.diagonal(offset=2)

array([3])

In [7]:
i=[0,1,2]
a[i,i]

array([1, 5, 9])

In [8]:
a[i,i]=2
a

array([[2, 2, 3],
       [4, 2, 6],
       [7, 8, 2]])

In [9]:
i=np.array([0,1])
a[i,i+1]=1
a

array([[2, 1, 3],
       [4, 2, 1],
       [7, 8, 2]])

In [10]:
a[i+1,i]=0
a

array([[2, 1, 3],
       [0, 2, 1],
       [7, 0, 2]])