In [1]:
%pylab
a=array([[1,2,3],[4,5,6]])
sum(a)

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


21

In [2]:
sum(a,axis=0)

array([5, 7, 9])

In [9]:
sum(a,axis=1)

array([ 6, 15])

In [5]:
a.prod()

720

In [6]:
prod(a,axis=0)

array([ 4, 10, 18])

In [10]:
from numpy.random import rand
a=rand(1,10)
%precision 3
a

array([[0.95 , 0.756, 0.773, 0.627, 0.995, 0.286, 0.212, 0.754, 0.913,
        0.533]])

In [11]:
a.min()

0.212

In [12]:
a.max()

0.995

In [14]:
a.min(axis=1)

array([0.212])

In [17]:
a.min(axis=0)

array([0.95 , 0.756, 0.773, 0.627, 0.995, 0.286, 0.212, 0.754, 0.913,
       0.533])

In [18]:
a.max(axis=0)

array([0.95 , 0.756, 0.773, 0.627, 0.995, 0.286, 0.212, 0.754, 0.913,
       0.533])

In [19]:
a.max(axis=1)

array([0.995])

In [21]:
from numpy.random import rand
a = rand(3, 4)
%precision 3
print(a)
a.min(axis=0)

[[0.964 0.07  0.432 0.189]
 [0.327 0.006 0.433 0.257]
 [0.417 0.562 0.872 0.89 ]]


array([0.327, 0.006, 0.432, 0.189])

In [22]:
from numpy.random import rand
a = rand(3, 4)
%precision 3
print(a)
a.min(axis=0)

[[0.943 0.816 0.75  0.323]
 [0.48  0.813 0.288 0.388]
 [0.252 0.739 0.002 0.941]]


array([0.252, 0.739, 0.002, 0.323])

In [23]:
a.argmin()

10

In [24]:
a

array([[0.943, 0.816, 0.75 , 0.323],
       [0.48 , 0.813, 0.288, 0.388],
       [0.252, 0.739, 0.002, 0.941]])

In [25]:
a.argmin(axis=0)

array([2, 2, 2, 0], dtype=int64)

In [27]:
a=array([[1,2,3],[4,5,6]])
a.mean()

3.500

In [28]:
a.mean(axis=-1)

array([2., 5.])

In [29]:
average(a,axis=0,weights=[2,3])

array([2.8, 3.8, 4.8])

In [30]:
a.std(axis=1)

array([0.816, 0.816])

In [31]:
a.var(axis=1)

array([0.667, 0.667])

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a.clip(3.3,6)

array([[3.3, 3.3, 3.3],
       [4. , 5. , 6. ]])

In [35]:
a.ptp(axis=1)

array([2, 2])

In [36]:
a.ptp()

5

In [37]:
a=array([1,2.5,3,66,1.23])
a.round()

array([ 1.,  2.,  3., 66.,  1.])

In [38]:
a.round(decimals=1)

array([ 1. ,  2.5,  3. , 66. ,  1.2])