In [2]:
import numpy as np
np.arange(4)

array([0, 1, 2, 3])

In [3]:
import numpy as np
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [4]:
np.arange(0, 2 * np.pi, np.pi / 4)

array([0.        , 0.78539816, 1.57079633, 2.35619449, 3.14159265,
       3.92699082, 4.71238898, 5.49778714])

In [5]:
np.arange(0, 2 * np.pi, np.pi / 4, dtype=np.float32)

array([0.       , 0.7853982, 1.5707964, 2.3561945, 3.1415927, 3.926991 ,
       4.712389 , 5.4977875], dtype=float32)

In [6]:
np.arange(1.5, 2.1, 0.3)

array([1.5, 1.8, 2.1])

In [7]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [8]:
np.logspace(0,2,5)

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [9]:
x_ticks = np.linspace(-1, 1, 5)
y_ticks = np.linspace(-1, 1, 5)

x, y = np.meshgrid(x_ticks, y_ticks)

In [10]:
x

array([[-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ],
       [-1. , -0.5,  0. ,  0.5,  1. ]])

In [11]:
y

array([[-1. , -1. , -1. , -1. , -1. ],
       [-0.5, -0.5, -0.5, -0.5, -0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0.5,  0.5,  0.5,  0.5,  0.5],
       [ 1. ,  1. ,  1. ,  1. ,  1. ]])

In [12]:
x_ticks = np.linspace(-1, 1, 5)
y_ticks = np.linspace(-1, 1, 5)

x, y = np.meshgrid(x_ticks, y_ticks, sparse=True)
x

array([[-1. , -0.5,  0. ,  0.5,  1. ]])

In [13]:
y

array([[-1. ],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 1. ]])

In [14]:
x, y = np.ogrid[-1:1:.5, -1:1:.5]

In [15]:
x

array([[-1. ],
       [-0.5],
       [ 0. ],
       [ 0.5]])

In [16]:
y

array([[-1. , -0.5,  0. ,  0.5]])

In [17]:
x, y = np.ogrid[-1:1:5j, -1:1:5j]
x,y

(array([[-1. ],
        [-0.5],
        [ 0. ],
        [ 0.5],
        [ 1. ]]), array([[-1. , -0.5,  0. ,  0.5,  1. ]]))

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.ones([2,3],dtype=np.float32)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [20]:
np.ones([2,3]) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [21]:
a=np.empty(2)
a

array([4.565e-321, 4.565e-321])

In [22]:
a.fill(9)
a

array([9., 9.])

In [23]:
a[:]=0
a

array([0., 0.])

In [24]:
a = np.arange(0, 10, 2.5)
a

array([0. , 2.5, 5. , 7.5])

In [25]:
np.empty_like(a)

array([0. , 2.5, 5. , 7.5])

In [26]:
np.zeros_like(a)

array([0., 0., 0., 0.])

In [27]:
np.ones_like(a)

array([1., 1., 1., 1.])

In [28]:
a

array([0. , 2.5, 5. , 7.5])

In [29]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])