In [5]:
import numpy as np
a=np.array([[1,2],
           [3,4],],
           dtype=np.uint8)

In [6]:
a.tostring()

b'\x01\x02\x03\x04'

In [7]:
a

array([[1, 2],
       [3, 4]], dtype=uint8)

In [8]:
a.tostring(order='F')

b'\x01\x03\x02\x04'

In [9]:
s = a.tostring()
a = np.fromstring(s, 
                  dtype=np.uint8)
a

F:\anaconda\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  This is separate from the ipykernel package so we can avoid doing imports until


array([1, 2, 3, 4], dtype=uint8)

In [10]:
a.shape=2,2
a

array([[1, 2],
       [3, 4]], dtype=uint8)